---
title: "Spatial Analysis"
output: html_notebook
---

```{r setup, include=FALSE}
MyFunctions::my_lib(c("ggmap","sf","tidyverse","tools","readr","data.table","maps"))
```


# Load data

## Ocean adapt data

```{r dat_exploded, eval = T, echo = T}

ocean_data <- readRDS("/Volumes/Enterprise/Data/pinskylab-OceanAdapt-966adf0/data_clean/dat_exploded.rds") %>% 
  filter(spp == "Centropristis striata",
       region %in% c("Northeast US Fall" , "Northeast US Spring")) #No more seasons


```

## Maps data

```{r maps_sf, eval = F, echo = T, results = 'hide'}

States <- c("maine", "new hampshire", "massachusets", "connecticut", "rhode island", "new york", "new jersey", "delaware", "maryland", "virginia", "north carolina") 

# US State Map (land)

land_sf <- st_as_sf(map("state", plot = FALSE, fill = TRUE)) %>% 
  filter(ID %in% States) 

# ggplot(us_map) +
  # geom_sf()

# US EEZ map

# path_world <- MyFunctions::my_path("G", extra_path = "Spatial/SAU/SAU_Shapefile")
path_world <- "~/Downloads/SAU_Shapefile"

# The File
fnam_world <- "SAUEEZ_July2015.shp"

# Load it!
eez_sf <- st_read(dsn = path_world,
                        layer =file_path_sans_ext(fnam_world)) %>% 
  rename(eez_name = Name) %>% 
  st_transform(crs = 4326) %>% # 4326
  # st_transform(crs = "+proj=eck4") %>% # for tbular plot
  st_simplify(preserveTopology = TRUE, dTolerance = 10000) %>% #0.1
  filter(eez_name == "USA (East Coast)")


# ggplot(eez_sf) +
# geom_sf(aes(),fill =NA)

# ggplot() +
#   geom_sf(data = World_eez_sf, aes(), color = "red") +
#   geom_sf(data = us_map, aes(), color = "blue")



# US state waters
# https://catalog.data.gov/dataset/federal-and-state-waters

# us_state_w <- rgdal::readOGR(dsn = "~/Downloads/FederalAndStateWaters/FederalAndStateWaters.gdb")
state_sf <-  st_read("~/Downloads/FederalAndStateWaters/FederalAndStateWaters.gdb") %>% 
  janitor::clean_names() %>% 
  mutate(jurisdicti = str_to_lower(jurisdicti)) %>% 
  filter(jurisdicti %in% States) %>% 
  st_transform(crs = 4326) # for matching projections

# plot <- state_sf %>%
  # st_simplify(preserveTopology = TRUE, dTolerance = 10000) %>%
  # ggplot()  +
  # geom_sf(aes(col = Jurisdicti))

# ggsave("plot.png",plot)


```


### Exploring spatial regions (a.k.a  buffers)

```{r}

# Buffer state waters

state_bf = st_buffer(state_sf, 405000)

# ------------------------------ #
# Testing and visualizing the buffer 
# ------------------------------ #

# p <- ggplot() +
#   geom_sf(data = eez_sf, aes(), fill = NA) +
#   geom_sf(data = state_bf, aes(color = jurisdicti), fill = NA) +
#   geom_sf(data = state_sf, aes(color = jurisdicti), fill = NA)
#   

# ggsave("testplotb.png",p)

# ------------------------------ #

#Join eez shapefile wih buffer

state_bf_ezz <- st_join(state_bf,eez_sf,join = st_contains)


pp <- ggplot(state_bf_ezz) +
  geom_sf()

ggsave("testplot.png",p)



```


### Map of smapling points

In this case the color gradient represents wtcpue (wet tones catch per unit of effort, haul hours) from 1972 to 2019. Grey dots represent `wtcpue = 0`

```{r survey_map, eval = T, echo = T, fig.width = 12, fig.height = 8}

ggplot(us_map) +
  geom_sf() +
  geom_sf(data = World_eez_sf, aes(), fill = "white") +
  geom_point(data = subset(ocean_data, wtcpue = 0),
             aes(
               x = lon,
               y = lat
             ),
             color = "grey95",
             size = 1
  ) +
  geom_point(data = subset(ocean_data, wtcpue > 0),
             aes(
               x = lon,
               y = lat,
               color = log10(wtcpue)
             ),
             size = 1
  ) +
  scale_color_distiller(palette = "Spectral", 
                       guide_legend(title = "WCPUE per Haul (log10)")) + 
  coord_sf(xlim = c(-76, -65),ylim = c(35, 45)) +
  MyFunctions::my_ggtheme_m() +
  facet_wrap(~region)

```


# Interpolation

## SF example A

https://swilke-geoscience.net/post/spatial_interpolation/


```{r interpolation, eval = T, echo = T}

subset_data <- ocean_data %>% 
  filter(region == "Northeast US Spring",
         wtcpue > 0) %>% 
  group_by(lon,lat) %>% 
  summarise(wtcpue = sum(wtcpue,na.rm = T))


# First let's define a bounding Box to extrapolate from
bbox <- c(
  "xmin" = min(subset_data$lon),
  "ymin" = min(subset_data$lat),
  "xmax" = max(subset_data$lon),
  "ymax" = max(subset_data$lat)
)

# Expand the grid
grd_template <- expand.grid(
  lon = seq(from = bbox["xmin"], to = bbox["xmax"], by = 0.5),
  lat = seq(from = bbox["ymin"], to = bbox["ymax"], by = 0.5)
)


# ---------------- #
# Visualize the box


# ggplot() +
#   geom_point(data = grd_template, aes(x = lon, y = lat), size = 0.1) +
#   geom_point(data = subset_data,
#   mapping = aes(x = lon, y = lat, color = wtcpue), size = 3) +
#   scale_color_gradientn(colors = c("blue", "yellow", "red")) +
#   theme_bw()

# ---------------- #


# Rasterize our grid
# expects a PROJ.4 string, see https://epsg.io/25833

crs_raster_format <- "+proj=longlat +datum=WGS84 +no_defs"

grd_template_raster <- grd_template %>% 
  dplyr::mutate(Z = 0) %>% 
  raster::rasterFromXYZ( 
    crs = crs_raster_format)

# The model

# Triangular Irregular Surface
fit_tin <- interp::interp( # using {interp}
  x = subset_data$lon,           # the function actually accepts coordinate vectors
  y = subset_data$lat,
  z = subset_data$wtcpue,
  xo = grd_template$lon,     # here we already define the target grid
  yo = grd_template$lat,
  output = "points"
) %>% 
  bind_cols() %>% 
  filter(!is.na(z))

ggplot(us_map) +
  geom_sf()+
  geom_sf(data = World_eez_sf, aes(), fill = "white")+
  geom_tile( data = fit_tin,
             aes(
               x = x,
               y = y,
               fill =z,
               colour = z
             )
  ) +
  geom_point(data = subset(subset_data, wtcpue > 0),
             aes(
               x = lon,
               y = lat
             ),
             alpha = 0.2
  ) +
  scale_color_distiller(palette = "Spectral", 
                        guide_legend(title = "WCPUE per Haul")) + 
  scale_fill_distiller(palette = "Spectral", 
                       guide_legend(title = "WCPUE per Haul")) +
  coord_sf(xlim = c(-76, -65),ylim = c(35, 45)) +
  MyFunctions::my_ggtheme_m()


```


